### ISSUE TITLE
Save Video

### ISSUE THREAD

**Issue by MikhilPastagia** [sunjinbo/oops#1]
Hi,
please let me know how can we save video which was editor using your code.
thank you.

**Comment by sunjinbo** [comment]
> Hi,
> please let me know how can we save video which was editor using your code.
> thank you.

Generally there are 3 ways to save video, you can reference google/grafika sample at here:

https://github.com/google/grafika/blob/master/app/src/main/java/com/android/grafika/RecordFBOActivity.java

**Comment by MikhilPastagia** [comment]
thanks for your replay.
but still not able to save using your reference. will you please implement it in your example ?
